Repository leapfrogtechnology/sports, pull requests merged in 2019-08, with the labels that each got.

#22 Set up DynamoDB
  .env.docker
  README.md
  api/.env.example
  api/README.md
  api/knexfile.ts
  api/package.json
  api/src/config/bookshelf.ts
  api/src/config/database.ts
  api/src/config/knex.ts
  api/src/controllers/slack.ts
  api/src/database/migrations/20190620174326_create_table_employees.ts
  api/src/database/migrations/20190620174327_create_table_user_roles.ts
  api/src/database/migrations/20190620174329_create_table_user_accounts.ts
  api/src/database/migrations/20190620174330_create_table_user_account_tokens.ts
  api/src/database/migrations/20190620174332_create_table_games.ts
  api/src/database/migrations/20190620174334_create_table_tournaments.ts
  api/src/database/migrations/20190620174335_create_table_categories.ts
  api/src/database/migrations/20190620174337_create_table_sub_tournaments.ts
  api/src/database/migrations/20190620174339_create_table_sub_tournament_players.ts
  api/src/database/migrations/20190620174340_create_table_teams.ts
  api/src/database/migrations/20190620174342_create_table_team_players.ts
  api/src/database/migrations/20190620174343_create_table_statuses.ts
  api/src/database/migrations/20190620174345_create_table_rounds.ts
  api/src/database/migrations/20190620174347_create_table_fixtures.ts
  api/src/database/migrations/20190620174348_create_table_fixture_images.ts
  api/src/database/migrations/20190620174350_create_table_football_scores.ts
  api/src/database/migrations/20190620174352_create_table_football_activity_types.ts
  api/src/database/migrations/20190620174353_create_table_football_score_activities.ts
  api/src/database/migrations/20190620174355_create_table_chess_winning_methods.ts
  api/src/database/migrations/20190620174356_create_table_chess_scores.ts
  api/src/database/migrations/20190620174359_create_table_carrom_board_scores.ts
  api/src/database/migrations/20190620174401_create_table_carrom_board_score_activities.ts
  api/src/database/migrations/20190620174403_create_table_table_tennis_scores.ts
  api/src/database/migrations/20190620174405_create_table_table_tennis_score_activities.ts
  api/src/database/migrations/20190620174407_create_table_counter_strike_scores.ts
  api/src/database/migrations/20190620174409_create_table_counter_strike_score_sets.ts
  api/src/database/migrations/20190620174411_create_table_counter_strike_score_set_activities.ts
  api/src/database/migrations/20190620174413_create_table_dota_scores.ts
  api/src/database/migrations/20190620174415_create_table_dota_score_activities.ts
  api/src/database/seeds/1_seed_chess_winning_methods_table.ts
  api/src/database/seeds/2_seed_football_activity_types_table.ts
  api/src/database/seeds/3_seed_employees_table.ts
  api/src/database/seeds/4_seed_user_roles_table.ts
  api/src/database/seeds/5_seed_user_accounts_table.ts
  api/src/database/stubs/migration.stub
  api/src/database/stubs/seed.stub
  api/src/index.ts
  api/src/models/BaseModel.ts
  api/src/models/Context.ts
  api/src/models/UserAccount.ts
  api/src/models/employees.ts
  api/src/resolverMap.ts
  api/src/routes.ts
  api/yarn.lock
  docker-compose.yml
  docker/db/Dockerfile
Labels: refactor

#17 SPORTS-183 Set up basic authentication system
  api/.env.example
  api/README.md
  api/docs/README.md
  api/docs/auth.md
  api/package.json
  api/src/config/appConfig.ts
  api/src/config/knex.ts
  api/src/database/migrations/20190707174411_alter_user_account_token_table.ts
  api/src/database/seeds/4_seed_user_roles_table.ts
  api/src/domains/employee.ts
  api/src/domains/token.ts
  api/src/domains/user.ts
  api/src/enums/userRoles.ts
  api/src/error/CustomError.ts
  api/src/error/DuplicateEntryError.ts
  api/src/error/InvalidPasswordError.ts
  api/src/error/JWTError.ts
  api/src/error/JWTExpiredError.ts
  api/src/error/MissingUserNameOrPasswordError.ts
  api/src/error/NotFoundError.ts
  api/src/error/ValidationError.ts
  api/src/index.ts
  api/src/lang/en.ts
  api/src/models/BaseModel.ts
  api/src/models/Employee.ts
  api/src/models/UserAccount.ts
  api/src/models/UserAccountToken.ts
  api/src/mutations/index.ts
  api/src/mutations/login.ts
  api/src/mutations/refreshAccessToken.ts
  api/src/mutations/signUp.ts
  api/src/queries/index.ts
  api/src/resolverMap.ts
  api/src/schema/schema.graphql
  api/src/service/token.ts
  api/src/service/user.ts
  api/src/types/cameize.d.ts
  api/src/utils/bcrypt.ts
  api/src/utils/errors.ts
  api/src/utils/jwt.ts
  api/src/utils/object.ts
  api/yarn.lock
Labels: enhancement, feature

#26 SPORTS-236 Add config API
  .travis.yml
  api/src/controllers/config.ts
  api/src/database/seeds/4_seed_user_roles_table.ts
  api/src/database/seeds/5_seed_user_accounts_table.ts
  api/src/domains/responses/config.ts
  api/src/enums/chessWinningMethods.ts
  api/src/enums/footballActivityTypes.ts
  api/src/enums/userRoles.ts
  api/src/index.ts
  api/src/mutations/login.ts
  api/src/mutations/refreshAccessToken.ts
  api/src/mutations/signUp.ts
  api/src/routes.ts
  api/src/services/config.ts
  api/src/services/token.ts
  api/src/services/user.ts
Labels: enhancement, feature

#24 SPORTS-189 Login page basic layout
  admin-app/.env.example
  admin-app/README.md.1
  admin-app/package-lock.json
  admin-app/package.json
  admin-app/public/favicon.ico
  admin-app/public/img/icons/android-chrome-192x192.png
  admin-app/public/img/icons/android-chrome-512x512.png
  admin-app/public/img/icons/apple-touch-icon-120x120.png
  admin-app/public/img/icons/apple-touch-icon-152x152.png
  admin-app/public/img/icons/apple-touch-icon-180x180.png
  admin-app/public/img/icons/apple-touch-icon-60x60.png
  admin-app/public/img/icons/apple-touch-icon-76x76.png
  admin-app/public/img/icons/apple-touch-icon.png
  admin-app/public/img/icons/favicon-16x16.png
  admin-app/public/img/icons/favicon-32x32.png
  admin-app/public/img/icons/msapplication-icon-144x144.png
  admin-app/public/img/icons/mstile-150x150.png
  admin-app/public/img/icons/safari-pinned-tab.svg
  admin-app/public/manifest.json
  admin-app/src/App.vue
  admin-app/src/assets/logo.png
  admin-app/src/router.ts
  admin-app/src/services/auth.ts
  admin-app/src/services/storage.ts
  admin-app/src/utils/httpHelper.ts
  admin-app/src/views/Dashboard.vue
  admin-app/src/views/Home.vue
  admin-app/src/views/Login.vue
  admin-app/tslint.json
  admin-app/yarn.lock
  api/src/services/user.ts
Labels: feature

#28 Update migrations
  api/docs/db.md
  api/src/constants/tables.ts
  api/src/database/migrations/20190620174330_create_table_user_account_tokens.ts
  api/src/database/migrations/20190620174334_create_table_tournaments.ts
  api/src/database/migrations/20190620174336_create_table_tournament_types.ts
  api/src/database/migrations/20190620174337_create_table_sub_tournaments.ts
  api/src/database/migrations/20190620174339_create_table_sub_tournament_images.ts
  api/src/database/migrations/20190620174339_create_table_sub_tournament_players.ts
  api/src/database/migrations/20190620174340_create_table_teams.ts
  api/src/database/migrations/20190620174353_create_table_football_score_activities.ts
  api/src/database/migrations/20190620174356_create_table_chess_scores.ts
  api/src/database/migrations/20190620174401_create_table_carrom_board_score_activities.ts
  api/src/database/migrations/20190620174405_create_table_table_tennis_score_activities.ts
  api/src/database/migrations/20190620174409_create_table_counter_strike_score_sets.ts
  api/src/database/migrations/20190620174411_create_table_counter_strike_score_set_activities.ts
  api/src/database/migrations/20190620174413_create_table_dota_scores.ts
  api/src/database/migrations/20190620174415_create_table_dota_score_activities.ts
  api/src/database/migrations/20190707174411_alter_user_account_token_table.ts
  api/src/database/seeds/1_seed_chess_winning_methods_table.ts
  api/src/database/seeds/1_seed_employees_table.ts
  api/src/database/seeds/2_seed_football_activity_types_table.ts
  api/src/database/seeds/2_seed_user_roles_table.ts
  api/src/database/seeds/3_seed_football_activity_types_table.ts
  api/src/database/seeds/4_seed_chess_winning_methods_table.ts
  api/src/database/seeds/5_seed_tournament_types_table.ts
  api/src/enums/footballActivityTypes.ts
  api/src/enums/tournamentTypes.ts
Labels: enhancement

#30 Handle errors through apollo and graphql
  admin-app/src/main.ts
  admin-app/src/utils/httpHelper.ts
  api/src/index.ts
  api/src/mutations/login.ts
  api/src/utils/errors.ts
Labels: enhancement

#31 SPORTS-231 Add middleware for validating tokens
  api/src/authenticator.ts
  api/src/error/TokenError.ts
  api/src/index.ts
  api/src/lang/en.ts
  api/src/middlewares/validateToken.ts
  api/src/models/Context.ts
  api/src/mutations/refreshAccessToken.ts
  api/src/mutations/signUp.ts
Labels: feature

#29 SPORTS-239 Add knockouts routes
  web-app/src/assets/sass/components/_common.scss
  web-app/src/assets/sass/components/_knockout.scss
  web-app/src/assets/sass/components/_manifest.scss
  web-app/src/assets/sass/components/_scoreCard.scss
  web-app/src/assets/sass/components/_scoreCardMinimal.scss
  web-app/src/assets/sass/utilities/_config.scss
  web-app/src/components/common/score-card/ScoreCardMinimal.vue
  web-app/src/components/common/sport-header/SportHeader.vue
  web-app/src/constants/routes.ts
  web-app/src/interfaces/interfaces.ts
  web-app/src/router.ts
  web-app/src/services/TeamService.ts
  web-app/src/views/common/knockouts/Knockouts.vue
  web-app/src/views/common/knockouts/partials/Tree.vue
  web-app/tslint.json
Labels: feature
