Repository leapfrogtechnology/sports, pull requests merged in 2019-06, with the labels that each got.

#2 Initiate vue app in typescript
  admin-app/.editorconfig
  admin-app/.env.docker
  admin-app/.eslintrc.js
  admin-app/.gitlab-ci.yml
  admin-app/.prettierrc
  admin-app/README.md
  admin-app/babel.config.js
  admin-app/package.json
  admin-app/postcss.config.js
  admin-app/public/img/icons/android-chrome-192x192.png
  admin-app/public/img/icons/android-chrome-512x512.png
  admin-app/public/img/icons/apple-touch-icon-120x120.png
  admin-app/public/img/icons/apple-touch-icon-152x152.png
  admin-app/public/img/icons/apple-touch-icon-180x180.png
  admin-app/public/img/icons/apple-touch-icon-60x60.png
  admin-app/public/img/icons/apple-touch-icon-76x76.png
  admin-app/public/img/icons/apple-touch-icon.png
  admin-app/public/img/icons/favicon-16x16.png
  admin-app/public/img/icons/favicon-32x32.png
  admin-app/public/img/icons/msapplication-icon-144x144.png
  admin-app/public/img/icons/mstile-150x150.png
  admin-app/public/img/icons/safari-pinned-tab.svg
  admin-app/public/index.html
  admin-app/public/manifest.json
  admin-app/public/robots.txt
  admin-app/src/App.vue
  admin-app/src/assets/images/logo-inverted.svg
  admin-app/src/assets/images/logo.svg
  admin-app/src/components/HelloWorld.vue
  admin-app/src/components/Logo.vue
  admin-app/src/main.ts
  admin-app/src/registerServiceWorker.ts
  admin-app/src/router.ts
  admin-app/src/shims-tsx.d.ts
  admin-app/src/shims-vue.d.ts
  admin-app/src/views/Home.vue
  admin-app/tsconfig.json
  admin-app/tslint.json
  admin-app/yarn.lock
Labels: feature

#4 Travis CI Configuration
  .travis.yml
  api/.upignore
  api/src/index.js
  api/up.json
Labels: feature

#5 Update READMEs
  README.md
  admin-app/README.md
  api/README.md
  docs/schema.png
  web-app/README.md
Labels: documentation

#9 Travis CI configuration
  .travis.yml
  api/.upignore
  api/src/server.ts
  api/up.json
Labels: enhancement

#8 Setup docker compose
  .env.docker
  .gitignore
  README.md
  admin-app/README.md
  api/.env.example
  api/README.md
  docker-compose.yml
Labels: documentation, enhancement

#10 Travis Slack Notification Enabled. Tokens Encrpyted
  .travis.yml
Labels: enhancement

#11 Add start script on package.json file
  api/package.json
Labels: enhancement

#12 Configure monorepo
  .travis.yml
  .travis/build-condition.sh
Labels: enhancement

#13 Document db schema
  README.md
  api/README.md
  api/docs/db.md
  api/knexfile.ts
  api/package.json
  api/src/database/migrations/20190620174326_create_table_employees.ts
  docs/schema.png
Labels: documentation
