Repository leapfrogtechnology/sports, pull requests merged in 2019-09, with the labels that each got.

#32 SPORTS-195 Add game CRUD
  admin-app/package.json
  admin-app/src/assets/sass/styles.scss
  admin-app/src/components/common/AddButton.vue
  admin-app/src/components/common/ItemsList.vue
  admin-app/src/components/common/Modal.vue
  admin-app/src/components/games/AddEditGameFormModal.vue
  admin-app/src/constants/modals.ts
  admin-app/src/domains/models/Game.ts
  admin-app/src/main.ts
  admin-app/src/services/auth.ts
  admin-app/src/services/games.ts
  admin-app/src/store/index.ts
  admin-app/src/store/modules/games.ts
  admin-app/src/store/modules/modal.ts
  admin-app/src/utils/httpHelper.ts
  admin-app/src/views/Dashboard.vue
  admin-app/src/views/Games.vue
  admin-app/yarn.lock
  api/docs/README.md
  api/docs/auth.md
  api/docs/games.md
  api/src/domains/game.ts
  api/src/domains/general.ts
  api/src/domains/responses/general.ts
  api/src/domains/user.ts
  api/src/index.ts
  api/src/middlewares/validateToken.ts
  api/src/models/BaseModel.ts
  api/src/models/Context.ts
  api/src/models/Game.ts
  api/src/mutations/game.ts
  api/src/mutations/index.ts
  api/src/mutations/signUp.ts
  api/src/queries/games.ts
  api/src/queries/index.ts
  api/src/schema/schema.graphql
  api/src/services/game.ts
  api/src/services/user.ts
  api/src/utils/jwt.ts
Labels: enhancement, feature

#36 SPORTS-240 Add username and logout on TopBar
  admin-app/src/assets/sass/styles.scss
  admin-app/src/components/TopBar.vue
  admin-app/src/constants/queries.ts
  admin-app/src/services/auth.ts
  admin-app/src/services/categories.ts
  admin-app/src/services/games.ts
  admin-app/src/services/rounds.ts
  admin-app/src/services/storage.ts
  admin-app/src/store/index.ts
  admin-app/src/store/modules/user.ts
  admin-app/src/views/Dashboard.vue
  api/docs/auth.md
  api/src/domains/user.ts
  api/src/mutations/index.ts
  api/src/mutations/user.ts
  api/src/schema/schema.graphql
  api/src/services/user.ts
Labels: enhancement, feature

#37 SPORTS-190 CRUD APIs for tournaments
  admin-app/package.json
  admin-app/src/assets/sass/styles.scss
  admin-app/src/components/tournaments/AddEditTournamentFormModal.vue
  admin-app/src/constants/modals.ts
  admin-app/src/constants/queries.ts
  admin-app/src/constants/routes.ts
  admin-app/src/domains/models/Tournament.ts
  admin-app/src/router.ts
  admin-app/src/services/tournaments.ts
  admin-app/src/store/index.ts
  admin-app/src/store/modules/games.ts
  admin-app/src/store/modules/tournaments.ts
  admin-app/src/views/Tournament.vue
  admin-app/src/views/Tournaments.vue
  admin-app/yarn.lock
  api/docs/README.md
  api/docs/tournaments.md
  api/package.json
  api/src/domains/tournament.ts
  api/src/models/Tournament.ts
  api/src/mutations/category.ts
  api/src/mutations/game.ts
  api/src/mutations/index.ts
  api/src/mutations/round.ts
  api/src/mutations/status.ts
  api/src/mutations/tournament.ts
  api/src/mutations/user.ts
  api/src/queries/category.ts
  api/src/queries/game.ts
  api/src/queries/index.ts
  api/src/queries/round.ts
  api/src/queries/status.ts
  api/src/queries/tournament.ts
  api/src/schema/schema.graphql
  api/src/services/tournament.ts
  api/src/utils/helpers.ts
  api/src/utils/validations.ts
  api/yarn.lock
Labels: feature

#48 SPORTS-186 Add api to sync the list of employees
  api/.env.example
  api/docs/README.md
  api/docs/employees.md
  api/package.json
  api/src/config/appConfig.ts
  api/src/domains/employee.ts
  api/src/mutations/employee.ts
  api/src/mutations/index.ts
  api/src/schema/schema.graphql
  api/src/services/employee.ts
  api/yarn.lock
Labels: enhancement, feature

#49 Sports 186 new
  api/src/services/employee.ts
Labels: enhancement

#27 SPORTS-187 Add a view for employess list
  admin-app/src/components/common/CustomButton.vue
  admin-app/src/components/common/ItemsList.vue
  admin-app/src/constants/queries.ts
  admin-app/src/domains/models/Employee.ts
  admin-app/src/services/employees.ts
  admin-app/src/store/index.ts
  admin-app/src/store/modules/employees.ts
  admin-app/src/views/Categories.vue
  admin-app/src/views/Employees.vue
  admin-app/src/views/Games.vue
  admin-app/src/views/Rounds.vue
  admin-app/src/views/Statuses.vue
  admin-app/src/views/Tournament.vue
  admin-app/src/views/Tournaments.vue
  api/docs/employees.md
  api/src/queries/employee.ts
  api/src/queries/index.ts
  api/src/schema/schema.graphql
  api/src/services/employee.ts
Labels: enhancement, feature

#50 SPORTS-238: Create interceptor
  admin-app/src/constants/queries.ts
  admin-app/src/main.ts
  admin-app/src/services/auth.ts
  admin-app/src/services/storage.ts
  admin-app/src/utils/http.ts
  admin-app/src/utils/httpHelper.ts
  admin-app/src/utils/interceptor.ts
  api/src/authenticator.ts
  api/src/config/appConfig.ts
  api/src/error/JWTError.ts
  api/src/error/JWTExpiredError.ts
  api/src/services/user.ts
  api/src/utils/jwt.ts
  api/src/utils/validations.ts
  web-app/src/router.ts
  web-app/src/services/CategoryService.ts
  web-app/src/services/FixtureService.ts
  web-app/src/services/PlayerService.ts
  web-app/src/services/TeamService.ts
  web-app/src/services/TournamentService.ts
Labels: enhancement, feature
